# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/johnny/Repositories/rpc_fun

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/johnny/Repositories/rpc_fun

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johnny/Repositories/rpc_fun/CMakeFiles /home/johnny/Repositories/rpc_fun//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johnny/Repositories/rpc_fun/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpc_sv

# Build rule for target.
rpc_sv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rpc_sv
.PHONY : rpc_sv

# fast build rule for target.
rpc_sv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/build
.PHONY : rpc_sv/fast

#=============================================================================
# Target rules for targets named rpc_cl

# Build rule for target.
rpc_cl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rpc_cl
.PHONY : rpc_cl

# fast build rule for target.
rpc_cl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/build
.PHONY : rpc_cl/fast

#=============================================================================
# Target rules for targets named rpc_common

# Build rule for target.
rpc_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rpc_common
.PHONY : rpc_common

# fast build rule for target.
rpc_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/build
.PHONY : rpc_common/fast

src/client.o: src/client.c.o

.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/src/client.c.s
.PHONY : src/client.c.s

src/rpc/list_clnt.o: src/rpc/list_clnt.c.o

.PHONY : src/rpc/list_clnt.o

# target to build an object file
src/rpc/list_clnt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/src/rpc/list_clnt.c.o
.PHONY : src/rpc/list_clnt.c.o

src/rpc/list_clnt.i: src/rpc/list_clnt.c.i

.PHONY : src/rpc/list_clnt.i

# target to preprocess a source file
src/rpc/list_clnt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/src/rpc/list_clnt.c.i
.PHONY : src/rpc/list_clnt.c.i

src/rpc/list_clnt.s: src/rpc/list_clnt.c.s

.PHONY : src/rpc/list_clnt.s

# target to generate assembly for a file
src/rpc/list_clnt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_cl.dir/build.make CMakeFiles/rpc_cl.dir/src/rpc/list_clnt.c.s
.PHONY : src/rpc/list_clnt.c.s

src/rpc/list_svc.o: src/rpc/list_svc.c.o

.PHONY : src/rpc/list_svc.o

# target to build an object file
src/rpc/list_svc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/src/rpc/list_svc.c.o
.PHONY : src/rpc/list_svc.c.o

src/rpc/list_svc.i: src/rpc/list_svc.c.i

.PHONY : src/rpc/list_svc.i

# target to preprocess a source file
src/rpc/list_svc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/src/rpc/list_svc.c.i
.PHONY : src/rpc/list_svc.c.i

src/rpc/list_svc.s: src/rpc/list_svc.c.s

.PHONY : src/rpc/list_svc.s

# target to generate assembly for a file
src/rpc/list_svc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/src/rpc/list_svc.c.s
.PHONY : src/rpc/list_svc.c.s

src/rpc/list_xdr.o: src/rpc/list_xdr.c.o

.PHONY : src/rpc/list_xdr.o

# target to build an object file
src/rpc/list_xdr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/src/rpc/list_xdr.c.o
.PHONY : src/rpc/list_xdr.c.o

src/rpc/list_xdr.i: src/rpc/list_xdr.c.i

.PHONY : src/rpc/list_xdr.i

# target to preprocess a source file
src/rpc/list_xdr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/src/rpc/list_xdr.c.i
.PHONY : src/rpc/list_xdr.c.i

src/rpc/list_xdr.s: src/rpc/list_xdr.c.s

.PHONY : src/rpc/list_xdr.s

# target to generate assembly for a file
src/rpc/list_xdr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/src/rpc/list_xdr.c.s
.PHONY : src/rpc/list_xdr.c.s

src/server.o: src/server.c.o

.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_sv.dir/build.make CMakeFiles/rpc_sv.dir/src/server.c.s
.PHONY : src/server.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpc_common.dir/build.make CMakeFiles/rpc_common.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rpc_cl"
	@echo "... rpc_common"
	@echo "... rpc_sv"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/rpc/list_clnt.o"
	@echo "... src/rpc/list_clnt.i"
	@echo "... src/rpc/list_clnt.s"
	@echo "... src/rpc/list_svc.o"
	@echo "... src/rpc/list_svc.i"
	@echo "... src/rpc/list_svc.s"
	@echo "... src/rpc/list_xdr.o"
	@echo "... src/rpc/list_xdr.i"
	@echo "... src/rpc/list_xdr.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

